spring:
  application:
    name: trello-app
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
      file-size-threshold: 1024MB
      location: attachment-file\\

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/trello
    username: postgres
    password: vetal54
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50

  flyway:
    enabled: true
    validate-on-migrate: true

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate.format_sql: true
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update

  messages:
    basename=validation

  mvc:
    view:
      prefix: /
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher

  jwt:
    header: Authorization
    secret: proselyte
    expiration: 604800

server:
  error:
    include-message: always
    include-exception: true
  port: 8081

application:
  swiche: false
  pagination-feature: true
